/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002113",
        "text-muted": "#94A3B8",
        "slate-border": "#334155",
        "surface-container": "#171f33",
        "background": "#0b1326",
        "on-secondary": "#003824",
        "growth-emerald": "#10B981",
        "primary": "#adc6ff",
        "inverse-primary": "#005ac2",
        "on-surface": "#dae2fd",
        "surface-container-high": "#222a3d",
        "surface-variant": "#2d3449",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#00285d",
        "surface-container-low": "#131b2e",
        "secondary-fixed-dim": "#4edea3",
        "outline": "#8c909f",
        "risk-crimson": "#EF4444",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-container": "#ff5451",
        "tertiary-fixed-dim": "#ffb3ad",
        "secondary-fixed": "#6ffbbe",
        "on-surface-variant": "#c2c6d6",
        "inverse-on-surface": "#283044",
        "surface-bright": "#31394d",
        "slate-surface": "#1E293B",
        "on-error": "#690005",
        "accent-blue": "#3B82F6",
        "tertiary": "#ffb3ad",
        "tertiary-fixed": "#ffdad7",
        "secondary-container": "#00a572",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-fixed-variant": "#930013",
        "on-primary-fixed-variant": "#004395",
        "error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        "surface-container-highest": "#2d3449",
        "primary-container": "#4d8eff",
        "on-background": "#dae2fd",
        "on-tertiary-container": "#5c0008",
        "secondary": "#4edea3",
        "on-secondary-container": "#00311f",
        "surface": "#0b1326",
        "error": "#ffb4ab",
        "on-primary": "#002e6a",
        "primary-fixed-dim": "#adc6ff",
        "surface-dim": "#0b1326",
        "on-primary-fixed": "#001a42",
        "on-tertiary": "#68000a",
        "surface-tint": "#adc6ff",
        "inverse-surface": "#dae2fd",
        "outline-variant": "#424754",
        "warning-amber": "#F59E0B",
        "surface-container-lowest": "#060e20",
        // Keeping previous semantic names for compatibility or fallback
        bg: "#0b1326",
        border: "#334155",
        accent: "#3B82F6",
        accent2: "#adc6ff",
        green: "#10B981",
        amber: "#F59E0B",
        red: "#EF4444",
        "text-1": "#dae2fd",
        "text-2": "#c2c6d6",
        "text-3": "#8c909f",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "lg": "24px",
        "sm": "8px",
        "unit": "4px",
        "gutter": "24px",
        "xs": "4px",
        "md": "16px",
        "xl": "32px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-jetbrains)", "monospace"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-jetbrains)", "monospace"],
        sans: ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
      },
      boxShadow: {
        "accent-glow": "0 0 15px -3px rgba(59, 130, 246, 0.3)",
        "green-glow": "0 0 15px -3px rgba(16, 185, 129, 0.3)",
        "red-glow": "0 0 15px -3px rgba(239, 68, 68, 0.3)",
        "glass-shadow": "0 8px 32px 0 rgba(0, 0, 0, 0.5)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};