/** @type {import('tailwindcss').Config} */
// Design tokens ported 1:1 from the "Equitas Precise" system used across
// all FinPilot Pro mockups (deep navy, Inter + JetBrains Mono, 4px grid).
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#373942",
        "surface-container-lowest": "#0c0e16",
        "surface-container-low": "#191b23",
        "surface-container": "#1d1f27",
        "surface-container-high": "#282a32",
        "surface-container-highest": "#32343d",
        "on-surface": "#e1e2ed",
        "on-surface-variant": "#c3c6d7",
        "inverse-surface": "#e1e2ed",
        "inverse-on-surface": "#2e3039",
        outline: "#8d90a0",
        "outline-variant": "#434655",
        "surface-tint": "#b4c5ff",
        primary: "#b4c5ff",
        "on-primary": "#002a78",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#0053db",
        secondary: "#b7c8e1",
        "on-secondary": "#213145",
        "secondary-container": "#3a4a5f",
        "on-secondary-container": "#a9bad3",
        tertiary: "#ffb596",
        "on-tertiary": "#581e00",
        "tertiary-container": "#bc4800",
        "on-tertiary-container": "#ffede6",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#0b1326",
        "on-background": "#e1e2ed",
        "surface-variant": "#32343d",
        "growth-emerald": "#4ade80",
        "risk-crimson": "#f87171",
        "accent-blue": "#2563eb",
        "warning-amber": "#ffb596",
        "slate-surface": "#1d1f27",
        "slate-border": "#434655",
        "text-muted": "#8d90a0",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "data-md": ["JetBrains Mono", "monospace"],
        "data-sm": ["JetBrains Mono", "monospace"],
        // Keep old ones for backward compatibility
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-lg": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "data-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "data-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        // Keep old ones for backward compatibility
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};