"""
backend/routes/export.py
PDF export endpoint — generates formatted A4 PDF from a research note.
Uses reportlab. Returns PDF as a streaming file download.
"""

import io
import json
import re
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT

from backend.store import get_note

router = APIRouter(prefix="/api/research", tags=["export"])

MARGIN = 2 * cm


@router.get("/{note_id}/json")
async def export_json(note_id: str):
    """
    Download the full structured report as JSON — the note, scorecard,
    financial data, sources, and recent news exactly as stored, with the
    internal `_web_results`/`_news_data`/`_financial_data_raw` context
    fields (used only to support revisions) stripped out.
    """
    note = get_note(note_id)
    if not note:
        return {"error": "Note not found"}

    exportable = {k: v for k, v in note.items() if not k.startswith("_")}
    payload = json.dumps(exportable, indent=2, default=str)
    buffer = io.BytesIO(payload.encode("utf-8"))
    buffer.seek(0)

    filename = f"{note.get('ticker', note_id)}_report.json".replace("/", "-")
    return StreamingResponse(
        buffer,
        media_type="application/json",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )

# Styles
def make_styles():
    styles = getSampleStyleSheet()
    title  = ParagraphStyle("Title",  fontName="Helvetica-Bold", fontSize=18, spaceAfter=4,  textColor=colors.HexColor("#1A1A2E"))
    meta   = ParagraphStyle("Meta",   fontName="Helvetica",      fontSize=10, spaceAfter=12, textColor=colors.HexColor("#555555"))
    h2     = ParagraphStyle("H2",     fontName="Helvetica-Bold", fontSize=13, spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#2C3E7A"))
    body   = ParagraphStyle("Body",   fontName="Helvetica",      fontSize=10, leading=15,    spaceAfter=6)
    footer = ParagraphStyle("Footer", fontName="Helvetica",      fontSize=8,  textColor=colors.HexColor("#999999"))
    return title, meta, h2, body, footer


@router.get("/{note_id}/pdf")
async def export_pdf(note_id: str):
    """Generate and return a formatted PDF for a research note."""
    note = get_note(note_id)
    if not note:
        return {"error": "Note not found"}

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=MARGIN,
    )

    title_style, meta_style, h2_style, body_style, footer_style = make_styles()
    story = []

    # Header
    company = note.get("company", "Company")
    ticker  = note.get("ticker", "")
    story.append(Paragraph(f"{company} — Equity Research Note", title_style))
    story.append(Paragraph(f"{ticker} &nbsp;·&nbsp; Generated by AlphaAgents &nbsp;·&nbsp; {note.get('created_at', '')[:10]}", meta_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CCCCCC"), spaceAfter=12))

    # Parse the markdown note into sections
    note_text = note.get("note", "")
    sections  = note_text.split("\n## ")

    for section in sections:
        lines = section.strip().split("\n")
        if not lines:
            continue

        header = lines[0].replace("# ", "").replace("## ", "").strip()
        content = "\n".join(lines[1:]).strip()

        if header and content:
            story.append(Paragraph(header, h2_style))
            # Clean up markdown formatting
            content_clean = content.replace("**", "").replace("*", "")
            # Only wrap actual "[Source: ...]" citations in the font tag —
            # a blind `.replace("]", "]</font>")` would append a stray,
            # unmatched </font> after every other "]" in the text (e.g. in
            # risk descriptions), which ReportLab's Paragraph markup parser
            # then chokes on.
            content_clean = re.sub(
                r"\[Source:([^\]]*)\]",
                r"<font color='#2C3E7A'>[Source:\1]</font>",
                content_clean,
            )
            for para in content_clean.split("\n\n"):
                if para.strip():
                    story.append(Paragraph(para.strip(), body_style))
            story.append(Spacer(1, 6))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.3, color=colors.HexColor("#CCCCCC"), spaceAfter=6))
    story.append(Paragraph("Generated by AlphaAgents · Multi-Agent Equity Research System · alphaagents.vercel.app", footer_style))

    doc.build(story)
    buf.seek(0)

    filename = f"{company.replace(' ', '_')}_Research_Note.pdf"
    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )